apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: pod-1
    purpose: pod-demo
spec:
  containers:
  - name: pod-1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod-2
    purpose: pod-demo
spec:
  affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pod-1
            topologyKey: "kubernetes.io/hostname"
  containers:
  - name: pod-2
    image: nginx

